import { getWhatsAppUrl } from '@/lib/whatsapp';
import { WhatsAppIcon } from '@/components/icons/WhatsAppIcon';
import { Reveal } from '@/components/animations/Reveal';

const faqs = [['¿Cómo compro mi iPhone?', 'Elige un modelo, selecciona su color y capacidad y pulsa “Consultar por WhatsApp”. Un asesor confirmará la disponibilidad, el precio final y las condiciones de pago y entrega antes de que realices tu compra.'], ['¿Qué diferencia hay entre sellado y de exhibición?', 'Sellado identifica un equipo sin abrir. Un equipo de exhibición ha estado expuesto o se ha utilizado para demostración. Solicita fotografías reales de la unidad, salud de batería, estado físico, accesorios incluidos y cobertura de garantía.'], ['¿Qué garantía tiene mi equipo?', 'La cobertura depende del equipo y su condición. Antes de comprar, solicita al asesor el plazo, los componentes cubiertos y las condiciones aplicables a esa unidad.'], ['¿Cómo coordino el pago y la entrega?', 'El pago y la entrega se coordinan directamente por WhatsApp. Indica tu ciudad o distrito para confirmar cobertura, costo y plazo de envío.'], ['¿Los precios y colores están confirmados?', 'Los precios publicados son referenciales. El precio final, la disponibilidad de cada color y capacidad, y los detalles de la unidad se confirman con un asesor antes de comprar.']];

export function FaqSection() {
  return <section id="preguntas" className="faq-section section container"><Reveal><div className="faq-intro"><span className="eyebrow">TODO CLARO, DESDE EL INICIO</span><h2>Antes de elegir.</h2><p>Las respuestas a tus primeras preguntas.</p><a className="text-link whatsapp-text-link" href={getWhatsAppUrl()} target="_blank" rel="noreferrer"><WhatsAppIcon /> ¿Tienes otra duda? <span aria-hidden="true">↗</span></a></div></Reveal><Reveal delay={.08}><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span className="faq-plus" aria-hidden="true" /></summary><div className="faq-answer"><p>{answer}</p></div></details>)}</div></Reveal></section>;
}
